[tool.poetry]
name = "simple-pipelayer"
version = "0.1.0"
description = "A simple implementation of PipeLayer"
authors = ["GreaterThan, LLC <info@greaterthan.solutions>"]
license = "FreeBSD"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pipelayer = "^0.7.0"
stringbender = "^0.3.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"
isort = "^5.13.2"
flake8 = "^7.1.1"
flake8-quotes = "^3.4.0"
mypy = "^1.11.1"
pre-commit = "^3.8.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
pytest-nunit = "^1.0.7"
coverage = "^7.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
ignore = "E501,W6"


[tool.pytest.ini_options]
testpaths = [
    "test"
]
addopts = [
    "-v",
    "-cov-report xml",
    "-cov-report term",
    "--strict-markers"
]
markers = [
    "integration",
    "unit",
    "happy",
    "sad"
]

[tool.coverage.report]
fail_under = 50
show_missing = true
